#!/usr/bin/env python3
"""Compile .qbb scripts into executable Python launchers."""
from __future__ import annotations

import argparse
import os
from pathlib import Path

TEMPLATE = '''#!/usr/bin/env python3
"""Auto-generated by qbbc.py from {source_name}."""
from __future__ import annotations
import importlib.util
from pathlib import Path
import sys

_RUNTIME_PATH = Path({runtime_path_literal})
if _RUNTIME_PATH.exists():
    _spec = importlib.util.spec_from_file_location("qbcgi_runtime", _RUNTIME_PATH)
    if _spec is None or _spec.loader is None:
        raise RuntimeError(f"Unable to load qbcgi runtime from {{_RUNTIME_PATH}}")
    _mod = importlib.util.module_from_spec(_spec)
    sys.modules[_spec.name] = _mod
    _spec.loader.exec_module(_mod)
    run_script = _mod.run_script
else:
    from qbcgi import run_script

SOURCE = {source_literal}

if __name__ == "__main__":
    print(run_script(SOURCE, cgi_mode={cgi_mode}), end="")
'''


def compile_qbb(input_path: Path, output_path: Path, *, cgi_mode: bool) -> None:
    source = input_path.read_text(encoding="utf-8")
    rendered = TEMPLATE.format(
        source_name=input_path.name,
        runtime_path_literal=repr(str(Path(__file__).with_name("qbcgi.py").resolve())),
        source_literal=repr(source),
        cgi_mode="True" if cgi_mode else "False",
    )
    output_path.write_text(rendered, encoding="utf-8")
    output_path.chmod(output_path.stat().st_mode | 0o111)


def main() -> int:
    ap = argparse.ArgumentParser(description="Compile .qbb into executable Python script")
    ap.add_argument("input", help="Path to input .qbb file")
    ap.add_argument("output", nargs="?", help="Output launcher path (default: <input>.py)")
    ap.add_argument("--cgi", action="store_true", help="Emit launcher that runs in CGI mode")
    args = ap.parse_args()

    in_path = Path(args.input)
    if not in_path.exists():
        raise SystemExit(f"Input script not found: {in_path}")

    out_path = Path(args.output) if args.output else in_path.with_suffix(".py")
    compile_qbb(in_path, out_path, cgi_mode=args.cgi)
    print(f"Compiled {in_path} -> {out_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
